---
- name: be sure htop is installed
  apt: pkg=htop state=installed
  tags: htop
- name: be sure screen is installed
  apt: pkg=screen state=installed
  tags: screen
- name: be sure git is installed
  apt: pkg=git state=installed
  tags: git
